// 會考題型 Ⅱ、Ⅲ（2.12）：用第二、三次段考的範圍出「會考式」的題目。
// 參考：會考的題型比例（單題重字彙、題組重圖表與推論；聽力＝辨識句意、基本問答、言談理解），題目、文章、聽力稿全部自編。
// 每題：sec＝題型、kp＝考點、why＝錯誤選項解析、lv＝難度（1 易、2 中、3 難；像會考依通過率分級）。

export const PASSAGES3 = {
  // ── 第二次段考範圍（Unit 3、Unit 4）──
  poolRules: {
    title: '🏊 SUNNY POOL',
    kind: 'notice',
    text: "Open: Tuesday to Sunday, 9:00 a.m. – 8:00 p.m. (closed on Mondays)\n① Take a shower before you swim.\n② Don't run around the pool. The floor is wet!\n③ Don't eat or drink here. You can eat in the Sun Room.\n④ Kids under six can't swim without a parent.\n⑤ Be quiet after 7:00 p.m. Some people are resting.\nHave fun!",
    zh: '晴天游泳池｜開放時間：星期二到星期日，上午 9 點到晚上 8 點（星期一休息）｜①游泳前先沖澡。②不要在泳池邊跑，地板是溼的！③這裡不可以吃東西或喝飲料，可以在陽光室吃。④六歲以下的小孩沒有家長不能游泳。⑤晚上 7 點以後請安靜，有人在休息。｜玩得開心！',
  },
  timetable: {
    title: '📚 Class 701 — Monday',
    kind: 'card',
    rows: [
      ['8:10 – 8:55', 'English 📖'],
      ['9:05 – 9:50', 'Math 🔢'],
      ['10:00 – 10:45', 'PE 🏀 (at the gym)'],
      ['10:55 – 11:40', 'Art 🎨'],
      ['12:00 – 1:00', 'Lunch 🍱'],
      ['1:10 – 1:55', 'Music 🎵'],
    ],
    zh: '701 班星期一課表｜8:10–8:55 英文｜9:05–9:50 數學｜10:00–10:45 體育（在體育館）｜10:55–11:40 美術｜12:00–1:00 午餐｜1:10–1:55 音樂',
  },
  groupChat: {
    title: '💬 Saturday Fun 🎉',
    kind: 'chat',
    me: 'Zoe',
    msgs: [
      ['Zoe', "Hi! What are you doing now? I'm at the park. It's a sunny day! ☀️"],
      ['Ben', "I'm doing my homework. 😩 Is Amy with you?"],
      ['Zoe', "Yes. She's riding her bike. Let's play basketball together at 3:00!"],
      ['Ben', "Sorry, I can't. My cousin is coming at 3:00."],
      ['Zoe', 'Then come at 4:00 and bring your cousin! We can all play.'],
      ['Ben', 'Great idea! See you at 4:00. 🏀'],
    ],
    zh: '星期六的樂趣｜Zoe：嗨！你現在在做什麼？我在公園，今天是晴天！｜Ben：我在寫功課。Amy 跟你在一起嗎？｜Zoe：對，她在騎腳踏車。三點一起打籃球吧！｜Ben：抱歉，我不行。我表弟三點要來。｜Zoe：那你四點來，帶你表弟一起！我們可以一起玩。｜Ben：好主意！四點見。',
  },
  // ── 第三次段考範圍（Unit 5、Unit 6）──
  festival: {
    title: '🌱 GREEN SCHOOL FESTIVAL — May 2027',
    kind: 'notice',
    text: "Come and have fun with your family!\n① May 8 (Sat.) 9:00 a.m. — Plant a tree with your class 🌳\n② May 9 (Sun.) 10:00 a.m. — Mother's Day concert: Say thank you to Mom with a song 🎵\n③ May 15 (Sat.) 2:00 p.m. — Animal show: Meet two rabbits, a turtle, and a big snake 🐍\n④ May 22 (Sat.) 9:00 a.m. — Clean-up day: Bring gloves and a water bottle\nThere are no classes on May 10 (Mon.).",
    zh: '綠色學校嘉年華（2027 年 5 月）｜和家人一起來玩！｜①5/8（六）上午 9 點：和全班一起種樹 ②5/9（日）上午 10 點：母親節音樂會，用一首歌對媽媽說謝謝 ③5/15（六）下午 2 點：動物表演，有兩隻兔子、一隻烏龜和一條大蛇 ④5/22（六）上午 9 點：清潔日，請帶手套和水壺｜5/10（一）不上課。',
  },
  petShop: {
    title: '🐾 HAPPY PET SHOP',
    kind: 'card',
    rows: [
      ['🐶 Dogs', '3 (one is a baby)'],
      ['🐱 Cats', '5'],
      ['🐰 Rabbits', '2 — new this week!'],
      ['🐢 Turtles', '0 (sorry, all sold)'],
      ['🐟 Fish', 'a lot! $30 each'],
      ['Open', 'Every day, 10:00 a.m. – 9:00 p.m.'],
    ],
    zh: '快樂寵物店｜狗 3 隻（一隻是幼犬）｜貓 5 隻｜兔子 2 隻，本週新到！｜烏龜 0 隻（抱歉，都賣完了）｜魚很多，每條 30 元｜每天營業，上午 10 點到晚上 9 點',
  },
  partyChat: {
    title: '💬 Party Time 🎂',
    kind: 'chat',
    me: 'Leo',
    msgs: [
      ['Leo', "Hi, Mia! My birthday is on June 3. It's a Thursday. 🎂"],
      ['Mia', 'Happy early birthday! Is there a party?'],
      ['Leo', 'Yes! But not on June 3. The party is on Saturday, June 5, at my house. 2:00 p.m.'],
      ['Mia', 'Great! Are there any animals at your house? I love dogs!'],
      ['Leo', "There aren't any dogs. But there are two cats and some fish. 🐱🐱🐟"],
      ['Mia', "Cats are cute, too! See you on the fifth!"],
    ],
    zh: '派對時間｜Leo：嗨，Mia！我的生日是 6 月 3 日，星期四。｜Mia：提前祝你生日快樂！有派對嗎？｜Leo：有！但不是 6 月 3 日。派對在星期六 6 月 5 日，在我家，下午 2 點。｜Mia：太好了！你家有動物嗎？我愛狗！｜Leo：沒有狗，但有兩隻貓和一些魚。｜Mia：貓也很可愛！5 號見！',
  },
}

export const MODULES3 = {
  // ───────────────────────── 會考題型 Ⅱ（Unit 3、Unit 4 的範圍）─────────────────────────
  k4: {
    unit: '會考導向 Ⅱ',
    title: '情境單題',
    icon: '💬',
    min: 8,
    items: [
      {
        t: 'learn',
        title: '會考單題：一半以上是「字彙」',
        show: '會考的單題裡，字彙題比文法題多（114 年：字彙 11 題、文法 8 題）。<br>字彙題不是考「這個字怎麼拼」，是考<b>情境</b>：前後句給線索，你要選「放進去最合理」的字。<br>Be careful! The floor is ___. → 要小心 → 地板是「溼的」→ wet',
        ask: 'Shh! The baby is ___. 空格最合理的字是？',
        opts: ['sleeping', 'singing', 'running'],
        a: 0,
        rule: 'Shh（噓）＝要安靜 → 寶寶在睡覺。先讀整句找線索，再看選項。',
        tip: '會考的字彙題常把線索放在「另一句」：先讀完兩句再選。',
      },
      {
        t: 'mcq', id: 'k4-01', sec: '情境單題',
        q: 'Be careful! The floor is ___. Don\'t run.',
        opts: ['wet', 'late', 'busy', 'free'],
        a: 0,
        kp: '情境字彙：Be careful ＋ Don\'t run → 地板溼',
        why: { 1: 'late 是「遲到的」，地板不會遲到。', 2: 'busy 是「忙的」，用在人。', 3: 'free 是「有空的、免費的」。' },
        ex: '要小心、不要跑 → 地板是溼的（wet）。',
        tags: ['vocab'],
      },
      {
        t: 'mcq', id: 'k4-02', sec: '情境單題',
        q: 'A: Can I use your phone? Mine is at home.\nB: ___ Here you are.',
        opts: ['Sure.', 'Yes, I can.', "No, you can't.", "I'm fine."],
        a: 0,
        kp: 'Can I…? 借東西：Sure. ＋ Here you are.',
        why: { 1: '問 Can I 的時候，回答要用 you，不是 I。', 2: '後面說 Here you are（拿去吧），所以是答應。', 3: "I'm fine 是回答 How are you?" },
        ex: '後一句 Here you are. 是把東西拿給對方 → 前面是答應：Sure.',
        tags: ['can', 'short'],
      },
      {
        t: 'mcq', id: 'k4-03', sec: '情境單題',
        q: '___ late for class again, Tim. The teacher is not happy.',
        opts: ["Don't be", "Don't", 'Not', "Isn't"],
        a: 0,
        kp: '否定祈使句＋形容詞：Don\'t be ＋ late',
        why: { 1: 'late 是形容詞，前面要有 be。', 2: '祈使句的否定是 Don\'t，不是 Not。', 3: "Isn't 是問句或敘述句用的，不是叫人做事。" },
        ex: '叫人「不要遲到」：Don\'t be late.（形容詞前面加 be）。',
        tags: ['imp', 'be'],
      },
      {
        t: 'mcq', id: 'k4-04', sec: '情境單題',
        q: 'A: What time is the concert?\nB: It\'s ___ seven thirty. Let\'s hurry!',
        opts: ['at', 'on', 'in', 'of'],
        a: 0,
        kp: '時間的介系詞：at 幾點',
        why: { 1: 'on 接星期幾或日期（on Friday）。', 2: 'in 接月份或早上、下午（in the morning）。', 3: 'of 不接時間。' },
        ex: '幾點 → at：at seven thirty。',
        tags: ['time', 'prep'],
      },
      {
        t: 'mcq', id: 'k4-05', sec: '情境單題',
        fig: { k: 'people', list: [['Amy', '👧', '🚴‍♀️']] },
        q: 'Look at the picture. Amy ___ in the park now.',
        opts: ['is riding a bike', 'rides a bike', 'is riding bike', 'riding a bike'],
        a: 0,
        kp: '看圖＋now：現在進行式 be ＋ V-ing',
        why: { 1: '有 now（現在），要用進行式。', 2: 'bike 是可數名詞，要有 a。', 3: '少了 be 動詞 is。' },
        ex: 'now → is ＋ riding；a bike 要有 a。',
        tags: ['ving', 'aan'],
      },
      {
        t: 'mcq', id: 'k4-06', sec: '情境單題',
        q: 'Mom, I can\'t do this math question. Can you help ___?',
        opts: ['me', 'I', 'my', 'mine'],
        a: 0,
        kp: '受格：動詞後面用 me',
        why: { 1: 'I 是主格，要放在動詞前面。', 2: 'my 後面要接名詞（my homework）。', 3: 'mine ＝ my ＋ 名詞，這裡是「幫我」。' },
        ex: 'help 是動詞，後面接受格 me。',
        tags: ['pron'],
      },
      {
        t: 'mcq', id: 'k4-07', sec: '情境單題',
        q: 'A: What day is it today?\nB: ___ We have PE class!',
        opts: ["It's Friday.", "It's May 5.", "It's ten o'clock.", "It's sunny."],
        a: 0,
        kp: 'What day → 回答星期幾',
        why: { 1: '日期是回答 What\'s the date?', 2: '幾點是回答 What time is it?', 3: '天氣是回答 How\'s the weather?' },
        ex: 'What day（星期幾）→ It\'s Friday.',
        tags: ['wh', 'time'],
      },
      {
        t: 'mcq', id: 'k4-08', sec: '情境單題',
        q: 'A: Let\'s go to the movies on Saturday.\nB: ___ I have a piano lesson that day. How about Sunday?',
        opts: ["Sorry, I can't.", 'Yes, I do.', 'Good idea!', "No, let's not."],
        a: 0,
        kp: '情境推論：後面說「那天有鋼琴課」→ 不能去',
        why: { 1: "Let's 的提議不用 Yes, I do 回答。", 2: '後面說那天有課、問星期天行不行，所以不是答應。', 3: '這是說「我們不要去」，但他後面在約別天，是自己不行。' },
        ex: '有鋼琴課 → 沒辦法去 → Sorry, I can\'t.；接著改約星期天。',
        tags: ['imp', 'can'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k4-09', sec: '情境單題',
        q: 'Leo is good at sports. He can swim, ride a bike, and play basketball, but he ___ at all.',
        opts: ["can't sing", 'can sing', "doesn't swim", 'is singing'],
        a: 0,
        kp: '情境推論：but ＝ 轉折 → 前面會、後面不會',
        why: { 1: 'but 後面要和前面相反：前面說他很會運動，後面應該是「不會」的事。', 2: '前面才說他會游泳。', 3: 'at all（一點也不）要配否定句。' },
        ex: 'but ＋ not … at all → 一點也不會唱歌：can\'t sing at all。',
        tags: ['can'],
        lv: 3,
      },
    ],
  },
  k5: {
    unit: '會考導向 Ⅱ',
    title: '圖表題組',
    icon: '📊',
    min: 12,
    items: [
      {
        t: 'learn',
        title: '非連續文本：公告、課表、群組訊息',
        show: '會考每年至少一篇「資訊圖表」：公告、課表、地圖、海報。<br>看這種題目的順序：<br>① 看<b>標題</b>知道這是什麼 ② 看<b>題目</b>要找什麼（時間？人？規則？）③ 回圖表只讀那一行 ④ 「Which is TRUE?」每個選項都回去對',
        ask: '題目問 What time is PE class?，你要先看課表的哪裡？',
        opts: ['從第一行讀到最後一行', '找 PE 那一行，看前面的時間', '看最下面的備註'],
        a: 1,
        rule: '先鎖定關鍵字（PE），再看它旁邊的資料。會考的圖表題不需要全部讀完。',
        tip: '注意「例外」：closed on Mondays、kids under six 這種小字常常就是考點。',
      },
      {
        t: 'mcq', id: 'k5-01', sec: '圖表題組', passage: 'poolRules',
        q: 'When can you swim at Sunny Pool?',
        opts: ['On Monday morning.', 'On Sunday afternoon.', 'At 8:30 p.m. on Friday.', 'At 7:00 a.m. on Saturday.'],
        a: 1,
        kp: '圖表找資訊：開放時間＋例外（星期一休息）',
        why: { 0: 'closed on Mondays：星期一休息。', 2: '晚上 8 點就關了。', 3: '早上 9 點才開。' },
        ex: 'Tuesday to Sunday、9:00 a.m. – 8:00 p.m. → 星期日下午可以。',
        tags: ['read', 'time'],
      },
      {
        t: 'mcq', id: 'k5-02', sec: '圖表題組', passage: 'poolRules',
        q: 'Ken is five years old. What is TRUE about him at Sunny Pool?',
        opts: ['He can swim with his mom or dad.', 'He can eat by the pool.', 'He can run around the pool.', "He can't swim at all."],
        a: 0,
        kp: '推論：under six ＋ without a parent → 有家長就可以',
        why: { 1: '規則③：不可以在這裡吃東西。', 2: '規則②：不可以在泳池邊跑。', 3: "規則④是說「沒有家長」不能游，有家長就可以。" },
        ex: "Kids under six can't swim without a parent. → 五歲的 Ken 要有爸爸或媽媽陪才能游。",
        tags: ['read', 'can'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k5-03', sec: '圖表題組', passage: 'poolRules',
        q: "It's 7:30 p.m. Amy's friends are talking and laughing loudly by the pool. What can the worker say to them?",
        opts: ['Be quiet, please.', 'Take a shower, please.', "Don't swim here.", 'Have fun!'],
        a: 0,
        kp: '把規則用在情境：7 點以後要安靜',
        why: { 1: '沖澡是游泳「前」的規則，他們現在是太吵。', 2: '規則沒有說不能游泳。', 3: '這是道別或歡迎時說的，不是糾正。' },
        ex: 'Be quiet after 7:00 p.m. → 7:30 很吵 → 請他們安靜。',
        tags: ['read', 'imp'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k5-04', sec: '圖表題組', passage: 'timetable',
        q: 'What time is PE class?',
        opts: ['At 10:00.', 'At 9:05.', 'At 10:55.', 'At 1:10.'],
        a: 0,
        kp: '圖表找資訊：PE 那一行',
        why: { 1: '9:05 是數學。', 2: '10:55 是美術。', 3: '1:10 是音樂。' },
        ex: '10:00 – 10:45 PE → 10 點。',
        tags: ['read', 'time'],
      },
      {
        t: 'mcq', id: 'k5-05', sec: '圖表題組', passage: 'timetable',
        q: "It's 11:20 on Monday. What are the students of Class 701 doing?",
        opts: ['They are drawing pictures.', 'They are eating lunch.', 'They are playing basketball.', 'They are singing.'],
        a: 0,
        kp: '時間落在哪一段 ＋ 課名換成「在做什麼」',
        why: { 1: '午餐是 12:00 才開始。', 2: '體育課 10:45 就結束了。', 3: '音樂課是下午 1:10。' },
        ex: '11:20 在 10:55 – 11:40 之間 → Art（美術）→ 在畫畫。',
        tags: ['read', 'time', 'ving'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k5-06', sec: '圖表題組', passage: 'timetable',
        q: 'Which is TRUE about the timetable?',
        opts: ['English class is before math class.', 'Lunch is one hour and ten minutes.', 'Art class is at the gym.', 'There are seven classes on Monday.'],
        a: 0,
        kp: 'Which is TRUE：每個選項回去對',
        why: { 1: '12:00 – 1:00 剛好一小時。', 2: '在體育館的是 PE。', 3: '課表上只有 5 堂課（午餐不是課）。' },
        ex: '8:10 English、9:05 Math → 英文在數學前面。',
        tags: ['read'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k5-07', sec: '圖表題組', passage: 'groupChat',
        q: 'What is Ben doing?',
        opts: ['He is doing his homework.', 'He is playing basketball.', 'He is riding a bike.', 'He is at the park.'],
        a: 0,
        kp: '訊息找資訊：Ben 自己說的那一則',
        why: { 1: '籃球是 Zoe 提議之後的事。', 2: '騎腳踏車的是 Amy。', 3: '在公園的是 Zoe 和 Amy。' },
        ex: "Ben：I'm doing my homework.",
        tags: ['read', 'ving'],
      },
      {
        t: 'mcq', id: 'k5-08', sec: '圖表題組', passage: 'groupChat',
        q: "Why can't Ben come at 3:00?",
        opts: ['His cousin is coming then.', 'He is at the park.', "He doesn't like basketball.", 'It is not a sunny day.'],
        a: 0,
        kp: '推論原因：Sorry, I can\'t 的下一句',
        why: { 1: '在公園的是 Zoe。', 2: '他最後說 Great idea，不是不喜歡。', 3: 'Zoe 說是晴天。' },
        ex: "Sorry, I can't. My cousin is coming at 3:00. → 三點表弟要來。",
        tags: ['read'],
      },
      {
        t: 'mcq', id: 'k5-09', sec: '圖表題組', passage: 'groupChat',
        q: 'How many people are playing basketball at 4:00?',
        opts: ['Four.', 'Two.', 'Three.', 'Five.'],
        a: 0,
        kp: '整合訊息：Zoe、Amy、Ben、表弟',
        why: { 1: '不只 Zoe 和 Ben。', 2: '別忘了 Ben 要帶表弟一起來。', 3: '訊息裡只有四個人。' },
        ex: 'Zoe ＋ Amy（在公園）＋ Ben ＋ Ben 的表弟 ＝ 4 人。',
        tags: ['read'],
        lv: 3,
      },
    ],
  },
  k6: {
    unit: '會考導向 Ⅱ',
    title: '會考聽力',
    icon: '🎧',
    min: 10,
    items: [
      {
        t: 'learn',
        title: '會考聽力：問題在「最後」才念',
        show: '會考的言談理解，<b>題目不印在考卷上</b>，對話講完才念問題，卷子上只有三個選項。<br>所以播放前要先看選項，猜「這題會問什麼」：<br>選項都是地點 → 注意聽地點；選項都是時間 → 注意聽數字。<br>每題都會播<b>兩次</b>：第一次抓大意，第二次確認。',
        ask: '選項是 At 2:00. / At 3:00. / At 4:00.，播放時要特別注意聽什麼？',
        opts: ['人名', '時間', '地點'],
        a: 1,
        rule: '選項長什麼樣，問題就會問什麼。先看選項，再按播放。',
        tip: "注意「更正」：被 not 否定的那個是錯的，答案是另一個：Not at 3:00, at 4:00. → 4:00；At 12:00, not at 8:00. → 12:00。",
      },
      {
        t: 'mcq', id: 'k6-01', sec: '辨識句意', audio: 'The boy is washing his dog in the yard.',
        q: '哪一張圖符合你聽到的句子？',
        pic: true,
        opts: ['👦🚿🐶', '👦🚿🐱', '👦🚶🐶'],
        a: 0,
        kp: '辨識句意：動作（washing）＋對象（dog）都要對',
        why: { 1: '聽到的是 dog，不是 cat。', 2: '是在洗狗，不是在遛狗。' },
        ex: 'washing his dog → 男孩在洗狗。',
        tags: ['listen', 'ving'],
      },
      {
        t: 'mcq', id: 'k6-02', sec: '辨識句意', audio: "It's a quarter to nine. Let's hurry!",
        fig: { k: 'clocks', list: [{ h: 8, m: 45 }, { h: 9, m: 15 }, { h: 9, m: 45 }] },
        q: '哪一個時鐘符合你聽到的時間？',
        opts: ['A', 'B', 'C'],
        a: 0,
        kp: 'a quarter to nine ＝ 8:45（差 15 分到 9 點）',
        why: { 1: '9:15 是 a quarter past nine。', 2: '9:45 是 a quarter to ten。' },
        ex: 'to ＝ 差幾分；a quarter ＝ 15 分 → 8:45。',
        tags: ['listen', 'time'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k6-03', sec: '辨識句意', audio: "Don't take pictures in the museum.",
        fig: { k: 'signs', list: [['📷', true, 'A'], ['📷', false, 'B'], ['🍔', true, 'C']] },
        q: '哪一個標誌符合你聽到的句子？',
        opts: ['A', 'B', 'C'],
        a: 0,
        kp: "辨識句意：Don't ＋ take pictures → 禁止拍照",
        why: { 1: 'B 是「可以拍照」。', 2: 'C 是「禁止吃東西」，但句子說的是拍照。' },
        ex: "Don't take pictures → 禁止拍照的標誌。",
        tags: ['listen', 'imp'],
      },
      {
        t: 'mcq', id: 'k6-04', sec: '基本問答', audio: 'What are you doing in the kitchen?',
        q: '選出最適合的回應。',
        opts: ["I'm making a cake for Mom.", 'I like the kitchen.', 'Yes, I am.'],
        a: 0,
        kp: '基本問答：What are you doing → 回答 be ＋ V-ing',
        why: { 1: '沒有回答「在做什麼」。', 2: 'What 開頭的問句不能用 Yes 回答。' },
        ex: "What are you doing? → I'm making a cake.",
        tags: ['listen', 'ving'],
      },
      {
        t: 'mcq', id: 'k6-05', sec: '基本問答', audio: 'What day is the English test?',
        q: '選出最適合的回應。',
        opts: ["It's on Thursday.", "It's at ten o'clock.", "It's English."],
        a: 0,
        kp: 'What day → 星期幾',
        why: { 1: '幾點是回答 What time。', 2: '問的是哪一天，不是哪一科。' },
        ex: 'What day → on Thursday。',
        tags: ['listen', 'time', 'wh'],
      },
      {
        t: 'mcq', id: 'k6-06', sec: '基本問答', audio: "Let's not take the bus. It's too slow.",
        q: '選出最適合的回應。',
        opts: ["OK. Let's take the MRT.", "Yes, let's take the bus.", 'No, I can\'t swim.'],
        a: 0,
        kp: "Let's not ＝ 不要搭公車 → 換別的",
        why: { 1: "對方說「不要」搭公車，不能回答搭公車。", 2: '和公車沒有關係。' },
        ex: "Let's not take the bus. → OK. Let's take the MRT.（改搭捷運）",
        tags: ['listen', 'imp'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k6-07', sec: '言談理解', audio: [['W', 'Good morning, everyone. This is Sunny Pool. The pool is closing at 12:00 today, not at 8:00 p.m. Workers are cleaning the Sun Room this afternoon. Please leave the pool before 12:00. Thank you.'], ['Q', 'What time is the pool closing today?']],
        q: '聽完廣播，回答聽到的問題。',
        opts: ['At 12:00.', 'At 8:00 p.m.', 'This afternoon.'],
        a: 0,
        kp: '言談理解：廣播裡的「更正」（not at 8:00 → at 12:00）',
        why: { 1: '8:00 是平常的關門時間，今天不是。', 2: '下午是工人在打掃的時間，不是關門時間。' },
        ex: 'closing at 12:00 today, not at 8:00 p.m. → 今天 12 點關。',
        tags: ['listen', 'time'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k6-08', sec: '言談理解', audio: [['B', 'Mom, can I go to the park now?'], ['W', 'Is your homework done?'], ['B', 'Almost. I\'m doing the last question.'], ['W', 'OK. Finish it first, and then you can go. Be back before six.'], ['Q', 'What is the boy doing now?']],
        q: '聽完對話，回答聽到的問題。',
        opts: ['He is doing his homework.', 'He is playing in the park.', 'He is coming home.'],
        a: 0,
        kp: '言談理解：問「現在」在做什麼，不是等一下要做什麼',
        why: { 1: '公園是寫完功課「之後」才能去。', 2: 'Be back before six 是媽媽的叮嚀，不是現在的動作。' },
        ex: "I'm doing the last question. → 他正在寫功課。",
        tags: ['listen', 'ving'],
      },
      {
        t: 'mcq', id: 'k6-09', sec: '言談理解', audio: [['G', 'Dad, what time is the movie?'], ['M', "It's at four thirty. What time is it now?"], ['G', "It's three forty-five. Can we take the bus?"], ['M', "No, the bus is slow. Let's ride our bikes."], ['Q', 'How are they going to the movie?']],
        q: '聽完對話，回答聽到的問題。',
        opts: ['By bike.', 'By bus.', 'On foot.'],
        a: 0,
        kp: '言談理解：女孩提議的（bus）被爸爸否定 → 答案在後面',
        why: { 1: "爸爸說 No, the bus is slow.", 2: '對話沒有說走路。' },
        ex: "Let's ride our bikes. → 騎腳踏車去。",
        tags: ['listen', 'imp'],
        lv: 2,
      },
    ],
  },

  // ───────────────────────── 會考題型 Ⅲ（Unit 5、Unit 6 的範圍）─────────────────────────
  k7: {
    unit: '會考導向 Ⅲ',
    title: '情境單題',
    icon: '💬',
    min: 8,
    items: [
      {
        t: 'learn',
        title: '文法題也要「看情境」',
        show: '會考的文法題不會只給一句：常常是 A、B 兩句對話，線索在另一句。<br>A: Are there any dogs at your house?　B: No, but there ___ two cats.<br>看 B：two cats 是複數 → there are。<br>先找「線索字」（two、any、a），再決定答案。',
        ask: 'A: How many birds are there in the tree?　B: There ___ only one. 空格要用？',
        opts: ['is', 'are'],
        a: 0,
        rule: '問句是複數（birds），但答句的主詞是 one（一隻）→ There is only one.',
        tip: 'There is／are 看「後面的第一個名詞」，不要被問句騙了。',
      },
      {
        t: 'mcq', id: 'k7-01', sec: '情境單題',
        q: "A: When is Teachers' Day in Taiwan?\nB: It's ___ September 28.",
        opts: ['on', 'in', 'at', 'to'],
        a: 0,
        kp: '日期前面用 on',
        why: { 1: 'in 接月份（in September），有日期就用 on。', 2: 'at 接幾點。', 3: 'to 不接日期。' },
        ex: '月份＋日期 → on September 28。',
        tags: ['date', 'prep'],
      },
      {
        t: 'mcq', id: 'k7-02', sec: '情境單題',
        q: 'Today is my grandma\'s ___ birthday. She is seventy now!',
        opts: ['seventieth', 'seventy', 'seventh', 'seventeenth'],
        a: 0,
        kp: '第幾個生日用序數：seventieth',
        why: { 1: 'seventy 是「70」，生日要用「第 70 個」。', 2: 'seventh 是「第 7 個」。', 3: 'seventeenth 是「第 17 個」。' },
        ex: '70 歲 → 第 70 個生日 → seventieth birthday。',
        tags: ['date'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k7-03', sec: '情境單題',
        q: "A: Are there any turtles in the pet shop?\nB: No, but there ___ two rabbits.",
        opts: ['are', 'is', 'am', 'be'],
        a: 0,
        kp: 'There is／are：看後面的名詞（two rabbits）',
        why: { 1: 'two rabbits 是複數。', 2: 'am 只配 I。', 3: '要用變化過的 be 動詞。' },
        ex: 'two rabbits（複數）→ there are。',
        tags: ['there', 'plural'],
      },
      {
        t: 'mcq', id: 'k7-04', sec: '情境單題',
        q: "A: ___ cats are there in the picture?\nB: Three. One is sleeping under the chair.",
        opts: ['How many', 'How old', 'How much', 'What'],
        a: 0,
        kp: '問數量：How many ＋ 複數名詞',
        why: { 1: 'How old 問年紀。', 2: 'How much 問不可數的量或價錢。', 3: 'What cats 不通；答句回答數量（Three）。' },
        ex: '答句是 Three（三隻）→ 問數量 → How many。',
        tags: ['there', 'wh'],
      },
      {
        t: 'mcq', id: 'k7-05', sec: '情境單題',
        fig: { k: 'pic', rows: ['🐟🐟🐟', '🐢'], bg: 'water' },
        q: 'Look at the picture. There are ___ fish and ___ turtle in the water.',
        opts: ['some; a', 'any; a', 'some; an', 'a; some'],
        a: 0,
        kp: 'some ＋ 複數／a ＋ 單數（turtle 子音開頭）',
        why: { 1: '肯定句用 some，any 用在否定句和問句。', 2: 'turtle 是子音開頭，用 a。', 3: 'fish 有三條（複數）要用 some，turtle 只有一隻要用 a。' },
        ex: '三條魚 → some fish；一隻烏龜 → a turtle。',
        tags: ['there', 'aan'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k7-06', sec: '情境單題',
        q: 'My birthday is ___ December. It is very cold then.',
        opts: ['in', 'on', 'at', 'from'],
        a: 0,
        kp: '月份前面用 in',
        why: { 1: 'on 要有日期（on December 5）。', 2: 'at 接幾點。', 3: 'from 是「從」。' },
        ex: '只有月份 → in December。',
        tags: ['date', 'prep'],
      },
      {
        t: 'mcq', id: 'k7-07', sec: '情境單題',
        q: 'Amy loves animals. She has a dog, two cats, and three ___ at home.',
        opts: ['rabbits', 'rabbit', 'rabbites', "rabbit's"],
        a: 0,
        kp: '數字＋複數名詞',
        why: { 1: 'three 後面要用複數。', 2: '複數直接加 s：rabbits。', 3: "rabbit's 是「兔子的」。" },
        ex: 'three ＋ rabbits。',
        tags: ['plural', 'vocab'],
      },
      {
        t: 'mcq', id: 'k7-08', sec: '情境單題',
        q: "A: What's the date today?\nB: ___ Tomorrow is Christmas!",
        opts: ["It's December 24.", "It's Thursday.", "It's winter.", "It's December."],
        a: 0,
        kp: '推論：明天是聖誕節（12/25）→ 今天 12/24',
        why: { 1: "What's the date 問日期，不是星期幾。", 2: '季節不是日期。', 3: '只有月份不算完整的日期，而且線索是「明天聖誕節」。' },
        ex: 'Tomorrow is Christmas（12 月 25 日）→ 今天是 December 24。',
        tags: ['date', 'wh'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k7-09', sec: '情境單題',
        q: "A: Is there any milk in the fridge? I want to make a cake.\nB: ___ Let's go buy some.",
        opts: ["No, there isn't.", 'Yes, there is.', "No, there aren't.", 'Yes, there are.'],
        a: 0,
        kp: '推論＋不可數：milk 用 is；要去買 → 沒有',
        why: { 1: '後面說要去買，所以是沒有。', 2: 'milk 不可數，要用 is，不是 are。', 3: 'milk 不可數，要用 there is／isn\'t。' },
        ex: "沒有牛奶才要去買 → No, there isn't.（milk 不可數用 is）。",
        tags: ['there', 'short'],
        lv: 3,
      },
    ],
  },
  k8: {
    unit: '會考導向 Ⅲ',
    title: '圖表題組',
    icon: '📊',
    min: 12,
    items: [
      {
        t: 'learn',
        title: '圖表題的三種問法',
        show: '① <b>找資訊</b>：What time…? How many…? → 回圖表找那一行<br>② <b>推論</b>：Which day can Amy go? → 把題目的條件（她星期六有事）和圖表合起來想<br>③ <b>Which is TRUE／NOT true?</b> → 四個選項一個一個回去對，不要憑印象',
        ask: '題目說「Ken 每個星期六都要上課」，問他可以參加哪一個活動。這是哪一種問法？',
        opts: ['找資訊', '推論：把條件和圖表合起來', 'Which is TRUE'],
        a: 1,
        rule: '題目多給的條件（星期六要上課）就是要你排除掉星期六的活動。',
        tip: '算錢、算人數的題目要在旁邊寫算式，不要心算。',
      },
      {
        t: 'mcq', id: 'k8-01', sec: '圖表題組', passage: 'festival',
        q: 'When is the Mother\'s Day concert?',
        opts: ['On May 9.', 'On May 8.', 'On May 15.', 'On May 10.'],
        a: 0,
        kp: '圖表找資訊：concert 那一行',
        why: { 1: '5/8 是種樹。', 2: '5/15 是動物表演。', 3: '5/10 是不上課的日子。' },
        ex: '② May 9 (Sun.) — Mother\'s Day concert。',
        tags: ['read', 'date'],
      },
      {
        t: 'mcq', id: 'k8-02', sec: '圖表題組', passage: 'festival',
        q: 'Ken has a piano lesson every Saturday morning. Which activity can he go to?',
        opts: ['The animal show.', 'Planting a tree.', 'Clean-up day.', 'He can\'t go to any activity.'],
        a: 0,
        kp: '推論：排除星期六「早上」的活動',
        why: { 1: '種樹是星期六早上 9 點。', 2: '清潔日也是星期六早上 9 點。', 3: '動物表演是星期六下午 2 點，早上的課上完就可以去。' },
        ex: '動物表演 May 15 (Sat.) 2:00 p.m. 是下午 → 可以去。',
        tags: ['read', 'time'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k8-03', sec: '圖表題組', passage: 'festival',
        q: 'Which is NOT true about the festival?',
        opts: ['There are three animals at the animal show.', 'Students plant trees with their classmates.', 'There are no classes on the day after the concert.', 'You need gloves on clean-up day.'],
        a: 0,
        kp: 'NOT true：找「錯的」那一個',
        why: { 1: '①：Plant a tree with your class。', 2: '音樂會 5/9，5/10 不上課。', 3: '④：Bring gloves。' },
        ex: 'two rabbits ＋ a turtle ＋ a big snake ＝ 四隻動物，不是三隻。',
        tags: ['read', 'plural'],
        lv: 3,
      },
      {
        t: 'mcq', id: 'k8-04', sec: '圖表題組', passage: 'petShop',
        q: 'How many cats are there in the shop?',
        opts: ['Five.', 'Three.', 'Two.', 'A lot.'],
        a: 0,
        kp: '圖表找資訊：Cats 那一行',
        why: { 1: '3 是狗。', 2: '2 是兔子。', 3: '很多的是魚。' },
        ex: '🐱 Cats — 5。',
        tags: ['read', 'there'],
      },
      {
        t: 'mcq', id: 'k8-05', sec: '圖表題組', passage: 'petShop',
        q: 'Mia wants a turtle. What can the shop worker say to her?',
        opts: ["Sorry, there aren't any turtles now.", 'There are two turtles. Which one?', 'Turtles are thirty dollars each.', 'The turtles are new this week.'],
        a: 0,
        kp: '把圖表用在情境：0 (all sold) → 沒有了',
        why: { 1: '兩隻的是兔子。', 2: '30 元的是魚。', 3: '本週新到的是兔子。' },
        ex: 'Turtles — 0 (sorry, all sold) → 店員會說：抱歉，現在沒有烏龜。',
        tags: ['read', 'there'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k8-06', sec: '圖表題組', passage: 'petShop',
        q: 'Ben buys two fish at the shop. How much does he pay?',
        opts: ['$60.', '$30.', '$90.', '$20.'],
        a: 0,
        kp: '算錢：$30 each × 2',
        why: { 1: '30 元是一條的價錢。', 2: '90 元是三條。', 3: '沒有這個價錢。' },
        ex: '$30 each → 兩條 ＝ $60。',
        tags: ['read'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k8-07', sec: '圖表題組', passage: 'partyChat',
        q: "When is Leo's party?",
        opts: ['On June 5.', 'On June 3.', 'On Thursday.', 'On June 4.'],
        a: 0,
        kp: '訊息陷阱：生日和派對不是同一天',
        why: { 1: '6/3 是生日，派對不在那天。', 2: '星期四是生日那天。', 3: '沒有提到 6/4。' },
        ex: 'The party is on Saturday, June 5.',
        tags: ['read', 'date'],
      },
      {
        t: 'mcq', id: 'k8-08', sec: '圖表題組', passage: 'partyChat',
        q: "What is TRUE about Leo's house?",
        opts: ['There are two cats and some fish.', 'There is a dog.', 'There are two dogs and a cat.', "There aren't any animals."],
        a: 0,
        kp: 'Which is TRUE：回去對 Leo 說的那一則',
        why: { 1: "There aren't any dogs.", 2: '是兩隻貓，不是兩隻狗。', 3: '有貓和魚。' },
        ex: "There aren't any dogs. But there are two cats and some fish.",
        tags: ['read', 'there'],
      },
      {
        t: 'mcq', id: 'k8-09', sec: '圖表題組', passage: 'partyChat',
        q: 'What does "the fifth" mean in the last message?',
        opts: ['June 5.', 'June 3.', '5:00 p.m.', 'Five people.'],
        a: 0,
        kp: '推論：the fifth ＝ 第 5 天（派對那天）',
        why: { 1: '6/3 是生日，Mia 說的是「派對那天見」。', 2: '派對是下午 2 點，不是 5 點。', 3: 'fifth 是序數（第五），不是數量。' },
        ex: 'See you on the fifth! → 5 號見 → June 5。',
        tags: ['read', 'date'],
        lv: 3,
      },
    ],
  },
  k9: {
    unit: '會考導向 Ⅲ',
    title: '會考聽力',
    icon: '🎧',
    min: 10,
    items: [
      {
        t: 'learn',
        title: '聽力的數字和日期',
        show: '會考聽力常考數字：日期、人數、價錢。<br>容易混的：<b>thirteen／thirty</b>、<b>fifteenth／fiftieth</b>、<b>June／July</b>。<br>-teen 重音在後面（thirTEEN），-ty 重音在前面（THIRty）。<br>聽到日期，心裡馬上換成數字：May the fifth → 5/5。<br>the second Sunday＝第二個星期日，不是 2 號。',
        ask: '聽到 "There are thirteen monkeys."，有幾隻猴子？',
        opts: ['13', '30'],
        a: 0,
        rule: 'thirTEEN 重音在後、尾音長；THIRty 重音在前、尾音短。',
        tip: '第一次播放先寫下數字，第二次播放確認是 -teen 還是 -ty。',
      },
      {
        t: 'mcq', id: 'k9-01', sec: '辨識句意', audio: 'There are two monkeys in the tree, and one is eating a banana.',
        q: '哪一張圖符合你聽到的句子？',
        pic: true,
        opts: ['🌳🐒🐒🍌', '🌳🐒🍌', '🌳🐒🐒🐒'],
        a: 0,
        kp: '辨識句意：數量（two）＋動作（eating a banana）',
        why: { 1: '只有一隻猴子，但句子說 two。', 2: '三隻猴子，而且沒有香蕉。' },
        ex: 'two monkeys ＋ one is eating a banana → 兩隻猴子、一根香蕉。',
        tags: ['listen', 'there'],
      },
      {
        t: 'mcq', id: 'k9-02', sec: '辨識句意', audio: "Mother's Day is on the second Sunday of May.",
        fig: { k: 'cal', mon: 'May 2027', first: 6, days: 31, mark: [9], emo: { 9: '💐' } },
        q: '哪一句和你聽到的意思一樣？',
        opts: ['母親節在五月的第二個星期日。', '母親節在五月二日。', '母親節在五月的第二個星期六。'],
        a: 0,
        kp: 'the second Sunday ＝ 第二個星期日（不是 2 號）',
        why: { 1: 'second Sunday 是「第二個星期日」，不是「2 日」。', 2: '聽到的是 Sunday，不是 Saturday。' },
        ex: 'the second Sunday of May → 五月的第二個星期日（2027 年是 5/9）。',
        tags: ['listen', 'date'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k9-03', sec: '辨識句意', audio: 'The turtle is under the chair, not on the chair.',
        q: '哪一張圖符合你聽到的句子？',
        pic: true,
        opts: ['🪑\n🐢', '🐢\n🪑', '🪑🐢'],
        a: 0,
        kp: '辨識句意：not 後面是錯的位置',
        why: { 1: '這是在椅子上。', 2: '這是在椅子旁邊。' },
        ex: 'under the chair → 在椅子下面。',
        tags: ['listen', 'prep'],
      },
      {
        t: 'mcq', id: 'k9-04', sec: '基本問答', audio: "When is your birthday?",
        q: '選出最適合的回應。',
        opts: ["It's on October 20.", "It's on Monday.", "I'm thirteen."],
        a: 0,
        kp: 'When is your birthday → 回答日期',
        why: { 1: '生日通常回答日期，不是星期幾。', 2: '這是回答 How old are you?' },
        ex: 'When → 日期：on October 20。',
        tags: ['listen', 'date'],
      },
      {
        t: 'mcq', id: 'k9-05', sec: '基本問答', audio: 'How many elephants are there in the zoo?',
        q: '選出最適合的回應。',
        opts: ['There are three.', 'Yes, there are.', 'They are big.'],
        a: 0,
        kp: 'How many → 回答數量',
        why: { 1: 'How many 開頭不能用 Yes 回答。', 2: '沒有回答數量。' },
        ex: 'How many → There are three.',
        tags: ['listen', 'there'],
      },
      {
        t: 'mcq', id: 'k9-06', sec: '基本問答', audio: 'Are there any rabbits in the pet shop?',
        q: '選出最適合的回應。',
        opts: ["Yes, there are two.", "Yes, it is.", "No, there isn't."],
        a: 0,
        kp: 'Are there…? → Yes, there are.／No, there aren\'t.',
        why: { 1: '問句是 Are there，不能用 it is 回答。', 2: '問句是 there are（複數），要用 aren\'t。' },
        ex: 'Are there any…? → Yes, there are two.',
        tags: ['listen', 'there', 'short'],
      },
      {
        t: 'mcq', id: 'k9-07', sec: '言談理解', audio: [['M', 'Welcome to Sunny Zoo! Today is a special day. There are two new baby lions on Lion Hill. The lion show is at three thirty, not at three. Please don\'t give food to the animals. Have a great day!'], ['Q', 'What time is the lion show today?']],
        q: '聽完廣播，回答聽到的問題。',
        opts: ['At 3:30.', 'At 3:00.', 'At 2:30.'],
        a: 0,
        kp: '言談理解：not at three → 答案是 not 前面的那一個',
        why: { 1: "廣播說 not at three。", 2: '沒有聽到 two thirty。' },
        ex: 'at three thirty, not at three → 3:30。',
        tags: ['listen', 'time'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k9-08', sec: '言談理解', audio: [['G', 'Dad, when is Grandma\'s birthday? Is it in June?'], ['M', 'No, it\'s in July. July 13.'], ['G', 'July 13? That\'s next Saturday! Let\'s make a card for her.'], ['M', 'Good idea. And let\'s buy some flowers, too.'], ['Q', 'When is Grandma\'s birthday?']],
        q: '聽完對話，回答聽到的問題。',
        opts: ['On July 13.', 'On June 13.', 'On July 30.'],
        a: 0,
        kp: '言談理解：女孩猜錯（June），爸爸更正（July）＋ thirteen',
        why: { 1: '女孩猜 June，爸爸說 No。', 2: 'thirteen（13）不是 thirty（30）。' },
        ex: "No, it's in July. July 13. → 7 月 13 日。",
        tags: ['listen', 'date'],
        lv: 2,
      },
      {
        t: 'mcq', id: 'k9-09', sec: '言談理解', audio: [['W', 'Look! There are so many animals in the picture. How many cats are there, Ben?'], ['B', 'Let me see. One, two, three… There are four cats. And there are two dogs.'], ['W', 'Are there any birds?'], ['B', "No, there aren't. But there is a big fish in the bowl."], ['Q', 'How many cats are there in the picture?']],
        q: '聽完對話，回答聽到的問題。',
        opts: ['Four.', 'Two.', 'Three.'],
        a: 0,
        kp: '言談理解：對話裡有很多數字，只找「問題問的」那一個',
        why: { 1: '兩隻的是狗。', 2: '他數到三是在數的過程，最後是四。' },
        ex: 'There are four cats. → 4 隻貓。',
        tags: ['listen', 'there'],
        lv: 2,
      },
    ],
  },
}

// 兩堂「會考題型」課：放在 Review 2、Review 3 後面（after），和那次段考一起看得到
export const LESSONS3 = [
  {
    id: 'L6k',
    after: 'L6',
    title: '會考題型 Ⅱ',
    sub: '情境單題・圖表題組・會考聽力（用第二次段考的範圍出會考式的題目）',
    exam: 'e2',
    modules: ['k4', 'k5', 'k6'],
    plan: [
      '這一組不是新範圍：把祈使句、can、時間、進行式放進會考的出題方式（字彙情境題、公告、課表、群組訊息、廣播）。',
      '字彙題先遮住選項，讓學生說「空格大概是什麼意思」，再看選項。',
      '圖表題請學生先說「題目要我找什麼」，再用手指出圖表的那一行。',
      '聽力：先看選項猜會問什麼，再播放；言談理解的問題在最後才念，提醒學生聽完整段。',
      '做完可以到「模擬段考」做一回「聽力練習卷」。',
    ],
  },
  {
    id: 'L9k',
    after: 'L9',
    title: '會考題型 Ⅲ',
    sub: '情境單題・圖表題組・會考聽力（用第三次段考的範圍出會考式的題目）',
    exam: 'e3',
    modules: ['k7', 'k8', 'k9'],
    plan: [
      '日期、序數、There is／are、some／any 放進對話和圖表裡考：線索常在「另一句」。',
      '嘉年華公告和寵物店的題目有「推論」和「算錢」：請學生在旁邊寫算式。',
      '聽力的數字：先聽重音分 -teen／-ty，第二次播放再確認。',
      '三次段考都考完後，做「第一冊會考模擬」：整冊混合、全部選擇題，交卷後看聽力和閱讀各答對幾題。',
    ],
  },
]
