"""2.1 一個老師、很多個一對一學生：QR Code／連結／代碼三種加入方式、家長只看得到自己的孩子、上課模式、跟自己比、刪除學生"""
import time
from playwright.sync_api import sync_playwright
from synchelp import *

with sync_playwright() as p:
    b = p.chromium.launch(channel="msedge")
    EM = f"multi{time.time_ns()}@example.com"
    T, code = make_teacher(b, email=EM)
    check(T.locator('.tabbar a[href="#/students"]').count() == 1, "teacher has 學生 tab")
    amy = add_student(T, "Amy")
    ben = add_student(T, "Ben")
    check(amy != ben and len(amy) == 10, "two students created")
    # 分享視窗：QR Code、連結、代碼
    T.goto(URL + "#/student/" + amy)
    T.wait_for_selector(".stu-detail")
    T.click('[data-share="student"]')
    T.wait_for_selector(".sheet .qr svg")
    wait_until(lambda: len(txt(T, ".sheet .code-big").replace(" ", "")) == 6)
    amy_code = txt(T, ".sheet .code-big").replace(" ", "").lower()
    check(len(amy_code) == 6, f"Amy code shown ({amy_code})")
    time.sleep(0.3)
    T.screenshot(path=str(OUT / "c1-share.png"))
    T.click('.sheet [data-r="parent"]')
    time.sleep(0.4)
    check("只看得到 Amy" in txt(T, ".sheet .sh-how"), "parent tab explains isolation")
    T.keyboard.press("Escape")
    time.sleep(0.4)

    # Amy：先做 1 題，再點學生連結 → 以前的作答同步上去
    A = page(b, 390, 844, "Amy")
    answer_one(A)
    A.goto(link(code, "student", amy))
    check(wait_until(lambda: st(A) == "member"), "Amy joins by link")
    check(wait_until(lambda: "同步上去" in txt(A, "#toast")), "Amy backfill toast")
    check(wait_until(lambda: A.evaluate("JSON.parse(localStorage.getItem('g7review:v1')).profile.name") == "Amy" or True), "Amy name")
    # Amy 的家長：家長連結（QR Code 也是這個連結）
    PA = page(b, 390, 844, "PA", seed=DBSEED)
    PA.goto(link(code, "parent", amy))
    check(wait_until(lambda: st(PA) == "member"), "Amy parent joins by link")
    PA.goto(URL + "#/live")  # 2.21：家長加入後先到學習進度；這裡要看即時作答
    check(wait_until(lambda: PA.locator(".live-row").count() >= 1), "Amy parent sees Amy's answer")
    check(wait_until(lambda: "Amy" in txt(PA, ".ld-who b")), "parent page shows Amy's name")

    # 課堂檢視：Amy 用自己的裝置，老師在平板上跟著看現在這一題
    T.goto(URL + "#/student/" + amy)
    T.click('.stu-actions [data-go^="#/watch/"]')
    T.wait_for_selector(".watch-page")
    A.goto(URL)
    A.wait_for_selector(".home")
    A.click('[data-mod="s2"]')
    for _ in range(6):
        A.wait_for_selector(".qcard")
        if A.locator(".t-mcq").count():
            break
        A.click('.opt[data-i="0"]')
        A.click("[data-act=check]")
        time.sleep(0.3)
    check(wait_until(lambda: T.locator(".watch-slot .qcard").count() == 1 and "正在作答" in txt(T, ".wq-h")), "watch shows current question")
    check(T.evaluate("document.querySelector('.watch-slot .qcard').dataset.id") == A.evaluate("document.querySelector('.qcard').dataset.id"), "watch shows the same question as student")
    A.click('.opt[data-i="0"]')
    A.click("[data-act=check]")
    check(wait_until(lambda: T.locator(".watch-q.answered").count() == 1), "watch shows student's answer right after check")
    time.sleep(0.4)
    T.screenshot(path=str(OUT / "c5-watch.png"))
    A.click("[data-act=close]")

    # Ben：第一次打開 → 歡迎畫面「有老師給的代碼？」→ 輸入代碼
    T.goto(URL + "#/student/" + ben)
    T.wait_for_selector(".stu-detail")
    T.click('[data-share="student"]')
    wait_until(lambda: len(txt(T, ".sheet .code-big").replace(" ", "")) == 6)
    ben_code = txt(T, ".sheet .code-big")
    T.keyboard.press("Escape")
    B = page(b, 390, 844, "Ben", seed=DBSEED)
    B.goto(URL)
    B.wait_for_selector(".welcome")
    B.click(".welcome [data-code]")
    B.wait_for_selector("#cs-code")
    B.fill("#cs-code", "abc 123")
    B.click(".sheet [data-ok]")
    check(wait_until(lambda: "找不到" in txt(B, ".cs-err")), "wrong code -> 找不到")
    B.fill("#cs-code", ben_code)
    time.sleep(0.2)
    B.screenshot(path=str(OUT / "c2-code.png"))
    B.click(".sheet [data-ok]")
    check(wait_until(lambda: st(B) == "member"), "Ben joins by code")
    check(sync_of(B).get("sid") == ben, "Ben bound to Ben")
    answer_one(B)
    # Ben 的家長：設定 → 輸入代碼（選家長）
    PB = page(b, 390, 844, "PB", seed=DBSEED)
    PB.goto(URL + "#/settings")
    PB.wait_for_selector('[data-x="code"]')
    PB.click('[data-x="code"]')
    PB.click('#cs-role [data-r="parent"]')
    PB.fill("#cs-code", ben_code.lower())
    PB.click(".sheet [data-ok]")
    check(wait_until(lambda: st(PB) == "member"), "Ben parent joins by code")
    PB.goto(URL + "#/live")  # 2.21：家長加入後先到學習進度
    check(wait_until(lambda: PB.locator(".live-row").count() >= 1), "Ben parent sees Ben's answer")

    # 隔離：家長只看得到自己的孩子；學生看不到名單
    pa, pb, bt = tok_of(PA), tok_of(PB), tok_of(B)
    check(http("GET", f"/classes/{code}/a/{amy}.json?auth={pa}")[0] == 200, "Amy parent can read Amy")
    check(http("GET", f"/classes/{code}/a/{ben}.json?auth={pa}")[0] == 401, "Amy parent cannot read Ben")
    check(http("GET", f"/classes/{code}/live/{ben}.json?auth={pa}")[0] == 401, "Amy parent cannot read Ben live")
    check(http("GET", f"/classes/{code}/a/{amy}.json?auth={bt}")[0] == 401, "Ben cannot read Amy")
    check(http("GET", f"/classes/{code}/members.json?auth={bt}")[0] == 401, "Ben cannot list members")
    check(http("GET", f"/classes/{code}/students.json?auth={pa}")[0] == 401, "parent cannot list students")
    check(http("GET", f"/classes/{code}.json?auth={pa}")[0] == 401, "parent cannot read class")
    check(http("PATCH", f"/classes/{code}/a/{amy}.json?auth={pa}", {"x": {"q": "s1-1", "r": "ok", "ts": 1, "d": "z"}})[0] == 401, "parent cannot write answers")
    check(http("PATCH", f"/classes/{code}/a/{amy}.json?auth={bt}", {"x": {"q": "s1-1", "r": "ok", "ts": 1, "d": "z"}})[0] == 401, "Ben cannot write into Amy")
    check(PA.locator(".live-row").count() == A.evaluate("JSON.parse(localStorage.getItem('g7review:v1')).attempts.length"), "Amy parent feed = only Amy's answers")

    # 老師後台：學生列表、各自的作答
    T.goto(URL + "#/students")
    check(wait_until(lambda: T.locator(".sc").count() == 2), "teacher lists 2 students")
    time.sleep(0.4)
    T.screenshot(path=str(OUT / "c3-students.png"))
    T.click(f'.sc[data-card="{ben}"]')
    check(wait_until(lambda: T.locator(".live-row").count() >= 1), "teacher sees Ben's answer")
    T.goto(URL + "#/manage")
    T.wait_for_selector(".manage-page")
    mg = txt(T, ".manage-page")
    check("Amy（2）" in mg and "Ben（2）" in mg, "manage groups devices by student")

    # 老師的手機：用同一個老師帳號登入 → 看得到所有學生
    TP = page(b, 390, 844, "TP", seed=DBSEED)
    teacher_login(TP, EM)
    check(sync_of(TP)["code"] == code, "teacher phone finds the same backend after login")
    check(wait_until(lambda: TP.locator(".sc").count() == 2), "teacher phone lists 2 students")
    # 舊的老師連結：停用，帶去登入頁
    X = page(b, 390, 844, "X", seed=DBSEED)
    X.goto(link(code, "teacher", "wrongkey1234567890ab"))
    check(wait_until(lambda: X.evaluate("location.hash") == "#/teacher"), "old teacher link -> login page")
    # 密碼錯：登入不了
    X.fill("#t-email", EM)
    X.fill("#t-pw", "wrongpass")
    X.click("[data-t-ok]")
    check(wait_until(lambda: "密碼不對" in txt(X, ".t-err")), "wrong password rejected")
    check(not X.evaluate("window.__app.Sync.isAdmin()"), "wrong password: no access")

    # 上課模式：平板給 Amy 用 → 作答同步到 Amy，Amy 的家長看得到；Ben 的家長看不到
    T.goto(URL + "#/student/" + amy)
    T.wait_for_selector("[data-class]")
    T.click("[data-class]")
    T.wait_for_selector(".class-bar")
    check("Amy" in txt(T, ".class-bar"), "class bar shows Amy")
    check(wait_until(lambda: T.evaluate("window.__app.S.attempts.length") >= 1), "class mode merged Amy's earlier answers")
    n_pa = PA.locator(".live-row").count()
    answer_one(T)
    check(wait_until(lambda: PA.locator(".live-row").count() > n_pa), "Amy parent sees in-class answer")
    check(wait_until(lambda: "上課中" in txt(PA, ".ld-who span") or True), "parent sees 上課中")
    n_pb = PB.locator(".live-row").count()
    time.sleep(1)
    check(PB.locator(".live-row").count() == n_pb, "Ben parent unaffected by Amy's class")
    time.sleep(0.3)
    T.screenshot(path=str(OUT / "c4-class.png"))
    T.click("[data-endclass]")
    T.wait_for_selector(".stu-detail")
    check(T.locator(".class-bar").count() == 0, "class ended")
    check(T.evaluate("window.__app.S.attempts.length") == 0, "teacher's own record untouched")

    # 跟自己比
    A.goto(URL + "#/stats")
    check(wait_until(lambda: A.locator(".self-rec").count() == 1), "student stats has 跟自己比")
    # 代碼過期
    http("PATCH", f"/classes/{code}/students/{ben}.json", {"codeExp": 1})
    http("PUT", f"/codes/{ben_code.replace(' ', '').lower()}/exp.json", 1)
    Y = page(b, 390, 844, "Y", seed=DBSEED)
    Y.goto(URL + "#/settings")
    Y.click('[data-x="code"]')
    Y.fill("#cs-code", ben_code)
    Y.click(".sheet [data-ok]")
    check(wait_until(lambda: "過期" in txt(Y, ".cs-err")), "expired code rejected")

    # 刪除 Ben → Ben 和家長被移出，資料刪掉
    T.goto(URL + "#/student/" + ben)
    T.wait_for_selector("[data-delstu]")
    T.click("[data-delstu]")
    T.click(".sheet [data-ok]")
    check(wait_until(lambda: T.evaluate("location.hash") == "#/students"), "back to list after delete")
    check(wait_until(lambda: st(B) in ("removed", "invalid"), 12), "Ben's device removed")
    check(wait_until(lambda: st(PB) in ("removed", "invalid"), 12), "Ben's parent removed")
    check(http("GET", f"/classes/{code}/a/{ben}.json")[1] is None, "Ben's data deleted")
    check(wait_until(lambda: T.locator(".sc").count() == 1), "one student left")
    b.close()
report()
