"""2.9 學生總覽＋老師登入：卡片、開放下一課、勾選多個學生、要處理的事、學生看不到沒開放的課、派作業自動開放、登出再登入、忘記密碼"""
import time
from playwright.sync_api import sync_playwright
from synchelp import *

EM = f"ov{time.time_ns()}@example.com"
with sync_playwright() as p:
    b = p.chromium.launch(channel="msedge")
    T, code = make_teacher(b, email=EM)
    amy = add_student(T, "Amy")
    ben = add_student(T, "Ben")
    A = page(b, 390, 844, "A")
    A.goto(link(code, "student", amy))
    wait_until(lambda: st(A) == "member")
    answer_one(A)
    # 總覽：每個學生一張卡片
    T.goto(URL + "#/students")
    check(wait_until(lambda: T.locator(".sc").count() == 2), "two student cards")
    check(wait_until(lambda: "Review 1" in txt(T, f'.sc[data-card="{amy}"] .sc-stats')), "card shows 開放到 (default first exam)")
    check(wait_until(lambda: "1" in txt(T, f'.sc[data-card="{amy}"] .sc-stats div:first-child b')), "card shows today's count")
    check(wait_until(lambda: "還沒開始練習" in txt(T, ".stu-page") or T.locator(".todo-card").count() == 0), "todo card ok")
    time.sleep(0.4)
    T.screenshot(path=str(OUT / "e1-overview.png"), full_page=True)
    # 開放的課：Amy 只開 Starter → 學生看不到 Unit 1、Unit 2
    T.click(f'.sc[data-card="{amy}"] .sc-units')
    T.wait_for_selector(".unit-row")
    for u in ("Unit 1", "Unit 2", "Review 1", "會考導向"):
        T.click(f'.unit-row[data-u="{u}"]')
    T.click(".sheet [data-ok]")
    check(wait_until(lambda: "Starter" in txt(T, f'.sc[data-card="{amy}"] .sc-stats')), "Amy now open to Starter")
    check(wait_until(lambda: "開放 Unit 1" in txt(T, f'.sc[data-card="{amy}"] .sc-acts')), "next button says 開放 Unit 1")
    A.evaluate("window.__app.Sync.fetchStu()")
    A.goto(URL)
    A.wait_for_selector(".home")
    check(wait_until(lambda: A.locator('[data-mod="u1a"]').count() == 0 and A.locator('.mod[data-mod="s1"]').count() == 1), "student sees only Starter")
    check("老師上課後開放" in txt(A, ".home"), "student sees locked note (no details)")
    check("Who's That" not in txt(A, ".home"), "locked lesson title hidden")
    time.sleep(0.3)
    A.screenshot(path=str(OUT / "e2-student-locked.png"), full_page=True)
    # 開放下一課（一鍵）→ 學生回到 App 就看到，還會提醒
    T.click(f'.sc[data-card="{amy}"] [data-act="next"]')
    check(wait_until(lambda: "已開放 Unit 1" in txt(T, "#toast")), "open next unit toast")
    A.evaluate("window.__app.Sync.fetchStu()")
    check(wait_until(lambda: A.locator('[data-mod="u1a"]').count() == 1), "student sees Unit 1 after opening")
    check(wait_until(lambda: "開放了新的課" in txt(A, "#toast")), "student told about new lesson")
    check(A.locator('[data-mod="u2a"]').count() == 0, "Unit 2 still hidden")
    # 選取兩個學生 → 一次派作業（含還沒開放的 Unit 2 → 自動開放）
    T.click("[data-pick]")
    T.click(f'.sc[data-card="{amy}"]')
    T.click(f'.sc[data-card="{ben}"]')
    check(wait_until(lambda: "已選 2 位" in txt(T, ".pick-bar")), "picked 2 students")
    T.screenshot(path=str(OUT / "e3-picking.png"))
    T.click("[data-pick-hw]")
    T.wait_for_selector(".hw-pick")
    T.click('.hw-pick[data-t="mod:u2a"]')
    T.click(".sheet [data-ok]")
    T.click(".sheet [data-send]")  # 派出前確認
    check(wait_until(lambda: "已派給 2 位學生" in txt(T, "#toast")), "homework sent to 2 students")
    # 派出後：每位學生各一則 LINE 訊息（連結不一樣）
    T.wait_for_selector(".sheet [data-copyone]")
    check(T.locator(".sheet [data-copyone]").count() == 2, "share step: one message per student")
    T.click(".sheet [data-close]")
    time.sleep(0.4)
    check(wait_until(lambda: len(http("GET", f"/classes/{code}/hw/{amy}.json")[1] or {}) == 1 and len(http("GET", f"/classes/{code}/hw/{ben}.json")[1] or {}) == 1), "each student got one homework")
    check((http("GET", f"/classes/{code}/students/{amy}/units.json")[1] or {}).get("Unit 2") is True, "homework auto-opened Unit 2 for Amy")
    # 勾選多個 → 開放課程（設定成一樣）
    T.click("[data-pick]")  # 完成
    T.click("[data-pick]")  # 再選一次
    T.click("[data-pick-all]")
    T.click("[data-pick-units]")
    T.wait_for_selector(".unit-row")
    T.click('.unit-row[data-u="會考導向"]')
    T.click(".sheet [data-ok]")
    check(wait_until(lambda: all((http("GET", f"/classes/{code}/students/{s}/units.json")[1] or {}).get("會考導向") is True for s in (amy, ben))), "batch units saved for both")
    T.click("[data-pick]")
    # 學生不能自己改開放的課
    stok = tok_of(A)
    check(http("PUT", f"/classes/{code}/students/{amy}/units/Unit%203.json?auth={stok}", True)[0] == 401, "student cannot open units")
    # 要處理的事：作業做完（直接寫一筆練習紀錄，等於學生做完了 u2a）
    A.evaluate("window.__app.Sync.fetchHw()")
    A.goto(URL)
    check(wait_until(lambda: A.locator(".hw-card [data-hw]").count() == 1), "student sees the homework")
    now = int(time.time() * 1000)
    http("PUT", f"/classes/{code}/s/{amy}/{now}-m_u2a-x.json", {"k": "m:u2a", "m": "u2a", "s": 90, "n": 10, "ts": now, "d": "x"})
    T.goto(URL + "#/students")
    check(wait_until(lambda: "作業做完了" in txt(T, ".stu-page"), 12), "todo: homework done")
    T.click(".todo-row.good .todo-x")
    check(wait_until(lambda: T.locator(".todo-row.good").count() == 0), "todo dismissed")
    # 登出 → 看不到；再登入 → 回到同一個後台
    T.goto(URL + "#/settings")
    T.click('[data-x="signout"]')
    T.click(".sheet [data-ok]")
    check(wait_until(lambda: not T.evaluate("window.__app.Auth.isTeacher()") and st(T) == "off"), "signed out")
    T.goto(URL + "#/students")
    time.sleep(0.5)
    check(T.locator(".sc").count() == 0, "no student cards after sign-out")
    T.goto(URL + "#/teacher")
    T.wait_for_selector(".teacher-page")
    T.fill("#t-email", EM)
    T.click("[data-t-forgot]")
    check(wait_until(lambda: "重設密碼" in txt(T, "#toast")), "password reset email")
    teacher_login(T, EM)
    check(sync_of(T)["code"] == code and wait_until(lambda: T.locator(".sc").count() == 2), "login again -> same backend")
    b.close()
report()
