"""成員管理：新成員通知、移除、允許重新加入、暫停加入、老師裝置可管理／取消管理；沒加入的人讀不到資料"""
import time, urllib.request
from playwright.sync_api import sync_playwright
from synchelp import *

with sync_playwright() as p:
    b = p.chromium.launch(channel="msedge")
    T, code = make_teacher(b)
    amy = add_student(T, "Amy")
    T.goto(URL + "#/settings")
    T.wait_for_selector('[data-x="manage"]')
    sset = txt(T, "#sync-sec")
    check(all(w not in sset for w in ("你是", "給自己", "自己的手機", "同意", "管理者")), "settings wording neutral")
    # 學生：先做 1 題，再點連結 → 直接加入
    S = page(b, 390, 844, "S")
    answer_one(S)
    S.goto(link(code, "student", amy))
    check(wait_until(lambda: st(S) == "member"), "student joins immediately")
    check(wait_until(lambda: "新成員加入" in txt(T, "#toast")), "teacher toast on new member")
    T.goto(URL + "#/")
    check(wait_until(lambda: "新成員加入" in T.locator("button.live-banner").inner_text()), "teacher home banner: 新成員加入")
    check(T.locator('.tabbar a[href="#/settings"] .badge').count() == 1, "settings tab badge")
    T.click("button.live-banner")
    T.wait_for_selector(".manage-page")
    check(wait_until(lambda: T.locator(".mg-new").count() == 1), "manage marks 新加入")
    check(wait_until(lambda: T.locator('.tabbar a[href="#/settings"] .badge').count() == 0), "badge cleared after viewing")
    time.sleep(0.3)
    T.screenshot(path=str(OUT / "b3-manage.png"), full_page=True)
    # 沒加入的人：有識別證也讀不到
    X = page(b, 390, 844, "X")
    X.goto(URL)
    X.wait_for_selector(".home")
    xtok = X.evaluate("window.__app.Auth.token()")
    for path in ("a", f"a/{amy}", "members", "live", "students", ""):
        check(http("GET", f"/classes/{code}{'/' + path if path else ''}.json?auth={xtok}")[0] == 401, f"non-member cannot read {path or 'class'}")
    # 學生不能看名單、不能把自己設成可管理
    stok, suid = tok_of(S), uid_of(S)
    check(http("GET", f"/classes/{code}/members.json?auth={stok}")[0] == 401, "student cannot list members")
    check(http("PUT", f"/classes/{code}/members/{suid}/admin.json?auth={stok}", True)[0] == 401, "student cannot self-promote")
    # 沒有老師帳號（匿名）：不能用老師身分加入、不能建立後台
    xuid = X.evaluate("window.__app.Auth.uid()")
    check(http("PUT", f"/classes/{code}/members/{xuid}.json?auth={xtok}", {"role": "teacher", "at": 1})[0] == 401, "anonymous cannot join as teacher")
    check(http("PUT", f"/classes/x{code}/owner.json?auth={xtok}", xuid)[0] == 401, "anonymous cannot create a backend")
    check(http("GET", f"/teachers/{uid_of(T)}.json?auth={xtok}")[0] == 401, "cannot read another teacher's account")
    # 學生、家長的畫面沒有老師入口
    X.goto(URL + "#/settings")
    X.wait_for_selector("#sync-sec")
    check("老師後台" not in txt(X, ".page") and X.locator('[data-v="teacher"]').count() == 0, "no teacher entry for students")
    # 成員管理：顯示老師帳號，沒有老師連結
    T.goto(URL + "#/manage")
    T.wait_for_selector(".manage-page")
    check("@example.com" in txt(T, ".manage-page") and "老師連結" not in txt(T, ".manage-page"), "manage shows account, no teacher link")
    # 暫停加入 → 新裝置被擋 → 打開後按再試一次就加入
    T.wait_for_selector("#open-seg")
    T.click('#open-seg [data-open="0"]')
    time.sleep(0.6)
    Y = page(b, 390, 844, "Y", seed=DBSEED)
    Y.goto(link(code, "parent", amy))
    check(wait_until(lambda: st(Y) == "closed"), "join closed -> state closed")
    check(wait_until(lambda: "暫停加入" in txt(Y, ".join-status")), "Y sees 暫停加入")
    T.click('#open-seg [data-open="1"]')
    time.sleep(0.6)
    Y.click(".sheet [data-rejoin]")
    check(wait_until(lambda: st(Y) == "member"), "Y joins after reopening")
    check(wait_until(lambda: Y.locator(".sheet .join-status").count() == 0), "status sheet closes after joining")
    # 移除學生 → 學生立刻看不到；重新整理也不會自己加回來
    T.goto(URL + "#/manage")
    wait_until(lambda: T.locator("[data-remove]").count() == 2)
    time.sleep(0.5)
    rows = T.locator(".mg-row:has([data-remove])")
    for i in range(rows.count()):
        if "學生" in rows.nth(i).inner_text():
            rows.nth(i).locator("[data-remove]").click()
            break
    T.click(".sheet [data-ok]")
    T.wait_for_selector(".sheet [data-undo]")  # 移除後：可以復原
    T.click(".sheet [data-close]")
    check(wait_until(lambda: st(S) == "removed", 12), "student detects removal")
    check(http("GET", f"/classes/{code}/a/{amy}.json?auth={stok}")[0] == 401, "removed student cannot read")
    S.goto(URL + "#/settings")
    check(wait_until(lambda: "被移出" in txt(S, ".page")), "student settings shows removed")
    S.reload()
    S.wait_for_selector(".page")
    time.sleep(1.5)
    check(st(S) == "removed", "reload stays removed")
    S.click("[data-rejoin]")
    time.sleep(1.5)
    check(st(S) in ("removed", "invalid"), "blocked device cannot rejoin by itself")
    T.goto(URL + "#/manage")
    check(wait_until(lambda: T.locator("[data-unblock]").count() == 1), "removed list shows student")
    T.click("[data-unblock]")
    time.sleep(0.8)
    S.goto(URL + "#/settings")
    S.wait_for_selector("[data-rejoin]")
    S.click("[data-rejoin]")
    check(wait_until(lambda: st(S) == "member"), "student rejoins after 允許重新加入")
    # 改名稱＋移除後復原（老師 10/9：測試家長頁時加入了自己的手機，怕刪錯）
    suid = uid_of(S)
    T.goto(URL + "#/manage")
    T.wait_for_selector(f'[data-rename="{suid}"]')
    T.click(f'[data-rename="{suid}"]')
    T.fill("#mg-name", "我的手機（測試）")
    T.click(".sheet [data-ok]")
    check(wait_until(lambda: "我的手機（測試）" in txt(T, ".manage-page")), "renamed device shows its new name")
    T.click(f'[data-remove="{suid}"]')
    T.wait_for_selector(".sheet [data-ok]")
    check("我的手機（測試）" in txt(T, ".sheet") and "不會被刪掉" in txt(T, ".sheet"), "remove confirm names the device and says records stay")
    T.click(".sheet [data-ok]")
    T.wait_for_selector(".sheet [data-undo]")
    T.click(".sheet [data-undo]")
    check(wait_until(lambda: (http("GET", f"/classes/{code}/members/{suid}.json")[1] or {}).get("dev") == "我的手機（測試）" and http("GET", f"/classes/{code}/blocked/{suid}.json")[1] is None), "undo puts the device back")
    T.screenshot(path=str(OUT / "a3-manage-undo.png"))
    b.close()
report()
